model:
  type: "GPS"                 # Model type: "GPS" for GPSConv
  channels: 2                # Size of each input sample
  # conv: None                  # The local message passing layer
  heads: 1                    # Number of multi-head-attentions
  # dropout: 0.2                # Dropout probability of intermediate embeddings
  act: "relu"                 # Activation function
  act_kwargs: {}              # Optional kwargs for activation function
  # norm: 'batch_norm'          # Normalization function
  norm_kwargs: {}             # Optional kwargs for normalization function
  # attn_type: 'multihead'      # Global attention type, multihead or performer
  # attn_kwargs: None           # Arguments passed to the attention layer
  num_classes: 2  # Number of classes for graph classification

training:
  batch_size: 32              # Batch size for training
  epochs: 100                 # Number of training epochs
  learning_rate: 0.01         # Learning rate
  weight_decay: 0.0005        # Weight decay (L2 regularization)
  device: "cuda"              # Device to use ("cuda" or "cpu")
